[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
autorestart=true

[program:flask]
command=gunicorn -w 2 -b 127.0.0.1:5000 app:app
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
autorestart=true
environment=
    PYTHONUNBUFFERED="1",
    PYRUS_ACCESS_TOKEN="%(ENV_PYRUS_ACCESS_TOKEN)s",
    PYRUS_LOGIN="%(ENV_PYRUS_LOGIN)s",
    BARKHAT_SSO_SECRET="%(ENV_BARKHAT_SSO_SECRET)s",
    SESSION_SECRET="%(ENV_SESSION_SECRET)s"
